/**
 * Copy the pinned Harper WebAssembly binary into `public/` so WXT ships it as a
 * plain `.wasm` file (streamed + browser-cached), instead of Vite inlining a
 * ~21 MB base64 string into the service worker on every build (§17.6).
 *
 * Runs from `prepare` (so `npm ci` in CI produces it) and again before builds.
 * The copied file is git-ignored; its provenance is this script + the lockfile.
 */

import {
  copyFileSync,
  mkdirSync,
  existsSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';

const ROOT = process.cwd();

const HARPER_PKG = resolve(ROOT, 'node_modules/harper.js/package.json');
if (!existsSync(HARPER_PKG)) {
  console.error('harper.js is not installed — run `npm install` first.');
  process.exit(1);
}
const harperVersion = (
  JSON.parse(readFileSync(HARPER_PKG, 'utf8')) as { version: string }
).version;

const SRC = resolve(ROOT, 'node_modules/harper.js/dist/harper_wasm_bg.wasm');
const DEST_DIR = resolve(ROOT, 'public/harper');
const DEST = resolve(DEST_DIR, 'harper_wasm_bg.wasm');
const MANIFEST = resolve(DEST_DIR, 'VERSION.json');

if (!existsSync(SRC)) {
  console.error(`Harper WASM not found at ${SRC}`);
  process.exit(1);
}

mkdirSync(DEST_DIR, { recursive: true });
copyFileSync(SRC, DEST);

const sha256 = createHash('sha256').update(readFileSync(DEST)).digest('hex');

writeFileSync(
  MANIFEST,
  JSON.stringify(
    {
      note: 'Generated by scripts/sync-harper-assets.ts — do not edit. Verifies the shipped engine matches the pinned harper.js.',
      harperVersion,
      file: 'harper_wasm_bg.wasm',
      bytes: readFileSync(DEST).byteLength,
      sha256,
    },
    null,
    2,
  ) + '\n',
);

console.log(
  `✓ Harper WASM synced: harper.js@${harperVersion}  (${(
    readFileSync(DEST).byteLength /
    1024 /
    1024
  ).toFixed(1)} MB, sha256 ${sha256.slice(0, 12)}…)`,
);
